version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:5.0.8
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  celery:
    build: .
    command: celery --app=university worker --loglevel=info
    volumes:
      - /var/lib/postgresql/data/
    depends_on:
      - web
      - redis
    env_file:
      - ./.env