# Generated by Django 3.2.4 on 2022-11-09 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.academicdiscipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дисциплина направления подготовки',
                'verbose_name_plural': 'Дисциплины направлений подготовки',
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('academic_disciplines', models.ManyToManyField(through='reports.FieldDiscipline', to='reports.AcademicDiscipline', verbose_name='Дисциплина')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_of_study', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('sex', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=10)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reports.fieldofstudy')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reports.group')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fielddiscipline',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.fieldofstudy', verbose_name='Направление подготовки'),
        ),
        migrations.AddConstraint(
            model_name='fielddiscipline',
            constraint=models.UniqueConstraint(fields=('field_of_study', 'academic_discipline'), name='unique_student_discipline'),
        ),
    ]
